version: '3.8'
services:
    terriamap:
        build: ./Terriamap-Telco/
        container_name: terriamap-telco
        ports:
            - 3001:3001
    geoserver:
        image: docker.osgeo.org/geoserver:2.25.0
        container_name: 'geoserver'
        ports:
            - 8080:8080
        environment:
        #    INSTALL_EXTENSIONS: "true"
        #    STABLE_EXTENSIONS: "sqlserver"
          - POSTGRES_JNDI_ENABLED=true
          - POSTGRES_HOST=postgis
          - POSTGRES_PORT=5432
          - POSTGRES_DB=geoserver
          - POSTGRES_USERNAME=geoserver
          - POSTGRES_PASSWORD=geoserver
          - POSTGRES_JNDI_RESOURCE_NAME=jdbc/postgres
        volumes:
            - ./geoserver/geoserver_data:/opt/geoserver_data
        healthcheck:
            test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
            interval: 1m
            retries: 3
            timeout: 20s
    postgis:
        image: postgis/postgis:latest
        container_name: 'postgis'
        ports:
          - 5432:5432
        environment:
            POSTGRES_USER: geoserver
            POSTGRES_PASSWORD: geoserver
            POSTGRES_DB: geoserver
        volumes:
            - ./postgis/postgis_data:/var/lib/postgresql/data
            - ./postgis/data:/root/data
        healthcheck:
            test: pg_isready -U geoserver -h localhost -t 5 || exit 1
            interval: 10s
            retries: 5
            timeout: 10s
    prefectserver:
        image: prefecthq/prefect:latest
        container_name: 'prefect-server'
        restart: always
        volumes:
            - ./prefect/prefect_data:/root/.prefect
        entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
        environment:
            - PREFECT_UI_URL=http://127.0.0.1:4200/api
            - PREFECT_API_URL=http://127.0.0.1:4200/api
            # If you want to access Prefect Server UI from anywhere other than the Docker host machine, you will need to change
            # PREFECT_UI_URL and PREFECT_API_URL to match the external hostname/IP of the host machine. For example:
            #- PREFECT_UI_URL=http://external-ip:4200/api
            #- PREFECT_API_URL=http://external-ip:4200/api
            - PREFECT_SERVER_API_HOST=0.0.0.0
            #- PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
            # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
            # - EXTRA_PIP_PACKAGES=prefect-aws
        ports:
            - 4200:4200
        profiles: ["server"]
    prefectagent:
        image: prefecthq/prefect:latest
        container_name: 'prefect-agent'
        restart: always
        entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
        environment:
            - PREFECT_API_URL=http://prefectserver:4200/api
            # Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
            # - PREFECT_API_KEY=YOUR_API_KEY
        profiles: ["agent"]
