version: '3.8'
services:
    terriamap:
        build: ./Terriamap-Telco/
        container_name: terriamap-telco
        ports:
            - 3001:3001
    geoserver:
        image: docker.osgeo.org/geoserver:2.25.0
        container_name: 'geoserver'
        ports:
            - 8080:8080
        environment:
        #    INSTALL_EXTENSIONS: "true"
        #    STABLE_EXTENSIONS: "sqlserver"
          - POSTGRES_JNDI_ENABLED=true
          - POSTGRES_HOST=postgis
          - POSTGRES_PORT=5432
          - POSTGRES_DB=geoserver
          - POSTGRES_USERNAME=geoserver
          - POSTGRES_PASSWORD=geoserver
          - POSTGRES_JNDI_RESOURCE_NAME=jdbc/postgres
        volumes:
            - ./geoserver/geoserver_data:/opt/geoserver_data
        healthcheck:
            test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
            interval: 1m
            retries: 3
            timeout: 20s
    postgis:
        image: postgis/postgis:latest
        container_name: 'postgis'
        ports:
          - 5432:5432
        environment:
            POSTGRES_USER: geoserver
            POSTGRES_PASSWORD: geoserver
            POSTGRES_DB: geoserver
        volumes:
            - ./postgis/postgis_data:/var/lib/postgresql/data
            - ./postgis/data:/root/data
        healthcheck:
            test: pg_isready -U geoserver -h localhost -t 5 || exit 1
            interval: 10s
            retries: 5
            timeout: 10s